apiVersion: embeddedcluster.replicated.com/v1beta1
kind: Config
spec:
  version: 1.28.4+ec.5
  unsupportedOverrides:
    k0s: |
      config:
        spec:
          workerProfiles:
          - name: ip-forward
            values:
              allowedUnsafeSysctls:
                - net.ipv4.ip_forward
