apiVersion: embeddedcluster.replicated.com/v1beta1
kind: Config
spec:
  version: 1.28.2+ec.2
  unsupportedOverrides:
    k0s: |-
      config:
        spec:
          api:
            extraArgs:
              service-node-port-range: 80-32767
